name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run checks
        run: |
          sudo apt-get -qq update || true
          sudo apt-get install -y bzr
          make ci
